version: '3.7' 
services: 
  ssh: 
    image zulissi/
    build:
      context: ./ssh
    deploy: 
      placement: 
        constraints: 
          - node.hostname == lambda-quad-3990-2080
      reservations:
        cpus: '4'
        memory: 500M
    volumes:
      - zulissi-home:/home/zulissi
    ports:
      - target: 22
        published: 2222
        protocol: tcp
        mode: host
  jupyter: 
    build:
      context: ./gpu-jupyter
    deploy: 
      placement: 
        constraints: 
          - node.hostname == lambda-quad-3990-2080
      reservations:
        cpus: '16'
        memory: 8G
    volumes:
      - zulissi-home:/home/zulissi
    ports:
      - target: 8888
        published: 9888
        protocol: tcp
        mode: host

volumes:
  zulissi-home:
