version: '3.7' 
services: 
  ssh: 
    image: zulissi/ssh
    deploy: 
      placement: 
        constraints: 
          - node.hostname == lambda-quad-3990-2080 # pick your computer
      limit:
        cpus: '4'
        memory: 500M
    volumes:
      - zulissi-home:/home/zulissi
    ports:
      - target: 22
        published: 2222 # pick your ssh port
        protocol: tcp
        mode: host
  jupyter: 
    image: zulissi/gpu_jupyter_environment
    deploy: 
      placement: 
        constraints: 
          - node.hostname == lambda-quad-3990-2080 # pick your computer
      reservations:
        cpus: '16'
        memory: 8G
    volumes:
      - zulissi-home:/home/zulissi
    ports:
      - target: 8888
        published: 9888 # pick your jupyter port
        protocol: tcp
        mode: host

volumes:
  zulissi-home:
